### ISSUE TITLE
使用pm2 启动项目发生错误

### ISSUE THREAD

**Issue by HereSinceres** [hefangshi/yog2-react-redux-demo#2]
使用pm2
错误提示： Cannot find module 'home:page/root/server.js'
启动命令 pm2 start app.js

备注：
使用forever正常

**Comment by HereSinceres** [comment]
补充信息：
```
Error: Cannot find module 'home:page/root/server.js'
   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
   at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
   at require (internal/modules/cjs/helpers.js:25:18)
   at Object.<anonymous> (/Users/xukai12/giki-fe/yog/app/home/lib/reactRenderAction.js:11:21)
   at Module._compile (internal/modules/cjs/loader.js:778:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
   at Module.load (internal/modules/cjs/loader.js:653:32)
   at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
   at Function.Module._load (internal/modules/cjs/loader.js:585:3)
   at Function.Module._load (/Users/xukai12/giki-fe/yog/node_modules/yog2-kernel/plugins/isomorphic/index.js:44:20)
   at Module.require (internal/modules/cjs/loader.js:692:17)
   at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
   at require (internal/modules/cjs/helpers.js:25:18)
   at Object.<anonymous> (/Users/xukai12/giki-fe/yog/app/home/action/index.js:11:29)
   at Module._compile (internal/modules/cjs/loader.js:778:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
   at Module.load (internal/modules/cjs/loader.js:653:32)
   at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
   at Function.Module._load (internal/modules/cjs/loader.js:585:3)
   at Function.Module._load (/Users/xukai12/giki-fe/yog/node_modules/yog2-kernel/plugins/isomorphic/index.js:44:20)
   at Module.require (internal/modules/cjs/loader.js:692:17)
   at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
```
